# Generated by Django 3.1.13 on 2021-12-14 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211030_0018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='weather',
        ),
    ]
