# Generated by Django 3.1.13 on 2021-12-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0005_delete_weather'),
    ]

    operations = [
        migrations.CreateModel(
            name='my_input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(upload_to='my_files')),
            ],
        ),
    ]
